name: Build@preview

on:
  pull_request:
    branches:
      - "gh/**"
      - "dev/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: "Clone preview"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: preview
          path: preview

      - name: "Setup Bun"
        uses: oven-sh/setup-bun@v2

      - name: "Install dependencies"
        run: bun install

      - name: Build
        run: bun run build

      - name: Clean up previous build
        run: |
          rm -rf ./preview/*
      
      - name: Copy preview build
        run: |
          rsync -a dist/* ./preview

      - name: Publish
        uses: EndBug/add-and-commit@v9
        with:
          cwd: "preview"
          add: "."
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Automatic commit, run id: ${{ github.run_id }}"
          push: true
      
