name: Bun CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: "Clone prod"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: prod
          path: prod

      - name: "Setup Bun"
        uses: oven-sh/setup-bun@v2

      - name: "Install dependencies"
        run: bun install

      - name: Build
        run: bun run build
      
      - name: Copy production build
        run: |
          rsync -a dist/* ./prod

      - name: Publish
        uses: EndBug/add-and-commit@v9
        with:
          cwd: "prod"
          add: "."
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Automatic commit, run id: ${{ github.run_id }}"
          push: true
      
